name: Daily Dashboard Update

on:
  schedule:
    - cron: '*/10 * * * *'   # mỗi 10 phút
  workflow_dispatch:         # cho phép chạy tay khi cần

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy jupyter nbconvert

      - name: Download CSV từ Google Sheets
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1LjMpHTw3LHS5XJQuKq464IEtgvaroteqBMY1BwPvye0/edit?usp=sharing" \
               -o notebook/SampleSuperstore.csv

      - name: Run notebook
        run: |
          cd notebook
          jupyter nbconvert --to notebook --execute superstore_dashboard.ipynb

      - name: Commit & push output
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/kpi.json data/parameter_chart.json
          git diff --cached --quiet || git commit -m "auto: update dashboard data $(date +'%Y-%m-%d')"
          git push